const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }
});

async function initializeSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      starts_at TIMESTAMPTZ NOT NULL
    );

    CREATE TABLE IF NOT EXISTS seats (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
      seat_number INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'reserved')),
      UNIQUE(event_id, seat_number)
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
      seat_id INTEGER NOT NULL UNIQUE REFERENCES seats(id),
      customer_name TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_seats_free_by_event
      ON seats(event_id, status, seat_number);
    CREATE INDEX IF NOT EXISTS idx_orders_event
      ON orders(event_id);
  `);
}

module.exports = { pool, initializeSchema };
